services:
  edu-genius:
    image: node:18.17.0
    command: make quero-boot-startup
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/edu-genius?schema=public"
    volumes:
      - .:/app:cached
      - edu-genius-node-modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edu-genius
    volumes:
      - ./db:/docker-entrypoint-initdb.d

volumes:
  edu-genius-node-modules:
